### ISSUE TITLE
Additional Character Management

### ISSUE THREAD

**Issue by N8teZero** [ExpDev07/legacy-rp-admin-v3#10]
**Is your feature request related to a problem? Please describe.**
More options to manage characters/players from the control panel would be really helpful. Things like setting a players job, resetting job, or character name changes. I know for job setting especially, it'd be much easier to do through a UI on the control panel than to use the commands in-game. 

**Describe the solution you'd like**
First step to this would be making each character's job viewable in the admin panel. Then when you click into a character, you'd have an option to modify the job/department/position.

**Comment by ExpDev07** [comment]
Yes, very good idea.

**Comment by ExpDev07** [comment]
Added.
