### ISSUE TITLE
Can not edit character information

### ISSUE THREAD

**Issue by Spitfire2k6** [ExpDev07/legacy-rp-admin-v3#100]
**Describe the bug**
When trying to update a character name it does not save.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'any character'
2. Update the name, click "Update Character"
3. Refresh
4. Nothing changes

**Comment by ExpDev07** [comment]
Is this an issue with every character?

**Comment by Spitfire2k6** [comment]
Yes

**Comment by ExpDev07** [comment]
Could you show the error you are getting?

**Comment by Spitfire2k6** [comment]
I wasn't getting an error. Nothing happens. Nuzi was saying he got an error though

**Comment by ExpDev07** [comment]
I need the error.

**Comment by Spitfire2k6** [comment]
I'm still not getting any errors yet it is not working. Is there anything else I can do to help? Screenshare?

**Comment by ExpDev07** [comment]
Issue is most likely due to a change in the database structure.

**Comment by Nuziatella** [comment]
No error anymore, it just doesn't save

**Comment by ExpDev07** [comment]
@milan60 can you confirm this issue?

**Comment by milan60** [comment]
Seems to be related to #101

**Comment by ExpDev07** [comment]
Fixed by new PR.
