### ISSUE TITLE
Can't Reset Jobs 

### ISSUE THREAD

**Issue by Ashraf2112** [ExpDev07/legacy-rp-admin-v3#101]
**Describe the bug**

**To Reproduce**
1. Go to Players Steam Name
2. Click on Reset Job 
3. Scroll down to nothing 
4. The Page is loading and nothing is resetting. 

**Expected behavior**
When clicking to reset any job, its not taking place. The page doesn't reload and the job can't be removed. 

**Screenshots**

https://streamable.com/zux0ni

**Comment by ExpDev07** [comment]
Issue is most likely due to a change in the database structure.

**Comment by ExpDev07** [comment]
Fixed by new PR.
