### ISSUE TITLE
Kicking players

### ISSUE THREAD

**Issue by milan60** [ExpDev07/legacy-rp-admin-v3#111]
**Describe the bug**
Kind of a bug but also a feature tbh. Whenever you ban someone from the panel, but they're in the city, you have to go in the city too and manually kick them. It would be cool if we could somehow integrate that in the panel (maybe a "kick" button that triggers some form of API on the server)

**To Reproduce**
1. Ban someone from panel
2. Join the server
3. Manually have to kick them

**Expected behavior**
Maybe a button or something in the panel like that to kick players from the game or banning someone from the panel would trigger an API endpoint.

**Screenshots**
N/A

**Comment by milan60** [comment]
@InZidiuZ

**Comment by InZidiuZ** [comment]
There's a route that lets you kick a player from the server. This route is restricted though and requires a token to go through. Here's an example snippet of it in NodeJS.

```js
const request = require("request");
const querystring = require("querystring");

let serverIp = "c3s1.op-framework.com";

let urlQueryString = querystring.stringify({
	steamIdentifier: "steam:110000111d99471",
	reason: "You have been banned for a reason.",
	removeReconnectPriority: false
});

let token = "?";

request(`https://${serverIp}/op-framework/execute/kickPlayer?${urlQueryString}`, {
	method: "POST",
	timeout: 5000,
	headers: {
		Authorization: "Bearer " + token
	}
});
```

**Comment by milan60** [comment]
Perfect, i'll add that as a button for the player profile, and you'll be able to set the token in your .env
