### ISSUE TITLE
OP-FW Logo not getting displayed in web panel

### ISSUE THREAD

**Issue by GuArDiAn-ops** [ExpDev07/legacy-rp-admin-v3#112]
**Describe the bug**
OP-FW logo doesnt load in webpanel
**To Reproduce**
Log into your admin webpanel on the top left the op-fw wont load

**Expected behavior**
Logo should be displayed correctly
**Screenshots**
https://gyazo.com/6621400a0a2cb55f45acf327cf3b3dec
Here is a console error https://gyazo.com/61549042f7c1d4efab114e8675cd5db2

**Comment by milan60** [comment]
Bug has been fixed in pull request #110

**Comment by milan60** [comment]
Bug has been fixed
