### ISSUE TITLE
Twitter page

### ISSUE THREAD

**Issue by mxttx** [ExpDev07/legacy-rp-admin-v3#123]
**Is your feature request related to a problem? Please describe.**
I would love to have a page for Twitter on the staff panel.

**Describe the solution you'd like**
This would be a dedicated page on the panel which includes a search for Twitter accounts in the database, along with the steam account/character page of who logged into a said account (over the last month).
This will help us instead of bothering InZidiuZ to look at who said person is, staff can become independent and work fast to resolve issues of trolling, or worse on Twitter.
It can even include a log of all recently sent tweets with the timestamp, but specifically searching for accounts and the steam account linked would be perfect.

**Describe alternatives you've considered**
N/A, although I guess there doesn't _need_ to be a separate page, but it would make sense for it to be it's own thing.

**Comment by milan60** [comment]
If @InZidiuZ is ok with it, i'd build something for this

**Comment by milan60** [comment]
Implemented in recent pull request #127

**Comment by milan60** [comment]
Deleting feature will come soon
