### ISSUE TITLE
This page is not working

### ISSUE THREAD

**Issue by xElten** [ExpDev07/legacy-rp-admin-v3#14]
is currently unable to process this request.
HTTP ERROR 500

 npm run dev/prod
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! missing script: dev/prod

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-30T21_02_48_956Z-debug.log

**Comment by ExpDev07** [comment]
Which page.

**Comment by xElten** [comment]
all pages

**Comment by xElten** [comment]
https://prnt.sc/rr0hvu

**Comment by xElten** [comment]
@ExpDev07 https://prnt.sc/rrs0um

**Comment by emtiazzahid** [comment]
@xElten 
I think it's node js version mismatch issue. please check you node version 

`npm -v

`
to update latest
`npm install npm@latest -g`

I am using _v12.10.0_

I just installed and run successfully.


Secondly, `gmp_init()` issue is from [gmp extension](https://stackoverflow.com/questions/40010197/how-to-install-gmp-for-php7-on-ubuntu/40010211)

**Comment by xElten** [comment]
@ExpDev07 @emtiazzahid https://prnt.sc/rx0k20 how can i add an staff

**Comment by ExpDev07** [comment]
@xElten Per https://github.com/ExpDev07/legacy-rp-admin-v3/blob/master/app/Player.php#L82-L90, they need to have a "staff" property, and it needs to be set to something else than null, 0, or false. For example, true, 1, or a staff ID such as "ADMIN-1".
