### ISSUE TITLE
Need a garage spawner at Eclipse Boulevard (77) 

### ISSUE THREAD

**Issue by Deaddro** [ExpDev07/legacy-rp-admin-v3#150]
**Is your feature request related to a problem? Please describe.**

[There is no garage in Eclipse Boulevard Manson]

**Describe the solution you'd like**

Need a garage mean spawner in Eclipse Boulevard Manson

**Describe alternatives you've considered**

If you can add garage spawner inside the garage it will be helpful 

**Additional context**

![07A1BAA2-6AA6-4CEB-A358-9A5DAC7E89A9](https://user-images.githubusercontent.com/71873145/124359471-046d6900-dc47-11eb-8ef8-69d9ed123e21.jpeg)

**Comment by milan60** [comment]
@Deaddro this is not something for the admin panel. You need to create your issue on the op-fw issue tracker https://github.com/InZidiuZ/op-framework-issue-tracker/issues
