### ISSUE TITLE
How can i be a contributor 

### ISSUE THREAD

**Issue by emtiazzahid** [ExpDev07/legacy-rp-admin-v3#17]
I have no steam key. because i didn't spend 5 USD on any game. i hope this shouldn't be a barrier for a developer to contribute using developer key of steam. can you please help me out from this situation. i really like to contribute. i am a fan of legacy rp

**Comment by ExpDev07** [comment]
Unfortunately you do need a steam key :/. The entire authentication system is through steam. I did not know it costed money to get one though... Looks like you'll have to just spend 5 bucks or maybe ask a friend to borrow their key (they can revoke it at any time and it does not grant you access to their account in any way as far as I'm concerned, so it should be fine security-wise).

Thanks for showing interest though!
