### ISSUE TITLE
Adding feature for superadmin to be able to edit player inventory

### ISSUE THREAD

**Issue by GuArDiAn-ops** [ExpDev07/legacy-rp-admin-v3#178]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

In the database there is a possibility to remove items from the players inventory including the house, vehicles as well as the character inventories. There could be an integration in the web panel to be able to remove or delete items from the inventory via the database without having to use the database directly thus this feature can be limited to Super admins. This feature can be added in the character section perhaps or in the players profile. This can make it easier during inventory wipes for random looting cases or intentionally wiping someones inventory for gain rather than calling them to support and wiping it this feature would make it easier.

**Describe alternatives you've considered**
Having the player join support and wiping inventory but if you have that happening everytime and you got a bigger player base this would make it a long process because people being unavailable this would just let a super admin to wipe the inventory and would be more efficient.
**Additional context**

**Comment by milan60** [comment]
Would have to get a sign off from @InZidiuZ for that

**Comment by InZidiuZ** [comment]
Super admins having the ability to do something like this wouldn't be a concern.

**Comment by milan60** [comment]
Implemented in the latest update

![button](https://i.imgur.com/kBIvBzK.png)  
![inventory](https://i.imgur.com/yMcFnLs.png)
