### ISSUE TITLE
Staff Member

### ISSUE THREAD

**Issue by DoPeMan17** [ExpDev07/legacy-rp-admin-v3#18]
You must be a staff member to use this webpanel! If you believe this is a mistake, contact a developer. 

How can i setup thes i am a stuff member where i can make this?

**Comment by ExpDev07** [comment]
Per https://github.com/ExpDev07/legacy-rp-admin-v3/blob/master/app/Player.php#L82-L90, they need to have a "staff" property (column in db), and it needs to be set to something else than null, 0, or false. For example, true, 1, or a staff ID such as "ADMIN-1". If not, they will be caught by this middleware: https://github.com/ExpDev07/legacy-rp-admin-v3/blob/master/app/Http/Middleware/StaffMiddleware.php, hence your error.

_Originally posted by @ExpDev07 in https://github.com/ExpDev07/legacy-rp-admin-v3/issues/14#issuecomment-612382494_
