### ISSUE TITLE
Gun Runs/ Plane Runs Logs

### ISSUE THREAD

**Issue by novapurple** [ExpDev07/legacy-rp-admin-v3#22]
**Is your feature request related to a problem? Please describe.**
Being able to make sure people are following the rules for the new gang rules set in place. Currently there is no way for us to know someone takes the coke plane or does gun runs unless they admit to it or staff is watching the places 24/7
**Describe the solution you'd like**
A log in the admin panel in staff documents that says for example “ NovaPurple has rented the plane “ or “NovaPurple has used Lesters computers”
**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. Something easy to read and easy to search for if you want to see logs for this 

**Additional context**

**Comment by ExpDev07** [comment]
Hello. You would be able to find this information in the servers logs if InziduZ has added it to the framework. You should direct this to him instead :)
