### ISSUE TITLE
Player Logs second page is not opening

### ISSUE THREAD

**Issue by rox98** [ExpDev07/legacy-rp-admin-v3#23]
**Describe the bug**
whenever i open any player database by using hex id on panel and than after i open that player logs it is working fine in first page but whenever i click on next page it will directly redirect me to all server logs second page means that player logs second page is not opening 

**To Reproduce**
1. Go to 'players' and search any player 
2. open that player database on panel
3. than scrolldown and open logs of that player
4. than after click on next button to open second page
5. than after it will directly redirect you to server logs second page instead of player logs second page

**Expected behavior**
if we press next button on player logs than it must be open second page of that player logs but right now server logs is opening so it is a bug.

**Screenshots**
https://gyazo.com/c64673fc01e0b3551080f0963c81f1dc

**Comment by ExpDev07** [comment]
@rox98 it should now be fixed. Remember to run ``npm run prod`` before starting the server :).
