### ISSUE TITLE
Not Being Able to Edit the License on site 

### ISSUE THREAD

**Issue by Princek101** [ExpDev07/legacy-rp-admin-v3#286]
**Describe the bug**
Menu for the License is not working. 

**To Reproduce**
1: Go To Charct  
2: The only option we see is "Update Chacrt" 

**Expected behavior**
We should be able to Edit and put the License that we want. 

**Screenshots**
https://prnt.sc/1t9rdg4

**Comment by milan60** [comment]
At the moment, the license editing feature is for super admins only
