### ISSUE TITLE
I cannot ban any person On Web Panel

### ISSUE THREAD

**Issue by Ronak31032002** [ExpDev07/legacy-rp-admin-v3#29]
I am admin of Legacy India Server and when i am trying to use the Web Panel i can unban add warning and i can search for every player but when it comes for banning someone I am again and again getting this error.
I tried changing my steam name, Logout Login done, Changed browser, Changed Internet Connection still i am getting the same error even in my phone 
![Screenshot_20200928-034405_Chrome](https://user-images.githubusercontent.com/53695724/94431204-99bc6800-01b2-11eb-85b7-9e2d766022f7.png)
![unknown](https://user-images.githubusercontent.com/53695724/94431211-9c1ec200-01b2-11eb-8ce0-3df7d4cdf633.png)

**Comment by Ronak31032002** [comment]
Rest of my friends For example Rest of Admins and Higher Admins are able to ban I'll leave some of my details here
Discord Tag - Warrior#7012
Hex Id 1100001175b4077
Steam Profile Link - https://steamcommunity.com/id/hellno123/

**Comment by ExpDev07** [comment]
I'll look into this, thanks.

**Comment by ExpDev07** [comment]
It looks like your steam name is the issue. Try to change your steam name to something that doesn't contain weird characters. Make sure to logout of the admin panel and back in after you've changed name to allow the update. 

Meanwhile I'll investigate the issue and try to publish a patch that will allow you to have weird names like that.

**Comment by Ronak31032002** [comment]
As you can check my hex id or steam link i have already changed my name
yesterday only and logged in using my only name Warrior Then too i tried
right now as well its showing me the same error

**Comment by Ronak31032002** [comment]
![Screenshot_20200928-034405_Chrome](https://user-images.githubusercontent.com/53695724/94484954-ceeca880-01fa-11eb-9338-ac06705d16a7.png)


I changed my name and you can see still i am facing :(

**Comment by Ronak31032002** [comment]
https://flareapp.io/share/q5YV4wxm

I got this from the error maybe this will be useful

**Comment by ExpDev07** [comment]
It is likely your in-game steam name then, something you can't change right now. I'll look into how to fix this, thanks.

**Comment by Ronak31032002** [comment]
What should i do now then bro?

**Comment by ExpDev07** [comment]
Hello. I tried using your name and banning a player locally on my machine and it worked fine? The issue could be the server's database encoding. Can you ban people in-game perfectly fine?

**Comment by Ronak31032002** [comment]
Thanks for the help Marius and Inz its solved now i can issue ban to people
from web panel thanks for the help <3

**Comment by ExpDev07** [comment]
Closing then.
