### ISSUE TITLE
Vehicle List

### ISSUE THREAD

**Issue by Nuziatella** [ExpDev07/legacy-rp-admin-v3#30]
**Is your feature request related to a problem? Please describe.**
Prevent abuse of people using cars as storage lockers to avoid interaction as well as see if a user received a vehicle correctly.

**Describe the solution you'd like**
Above the Edit command of users have a vehicles button to allow viewing of all vehicles currently owned by that individual. 

**Describe alternatives you've considered**
Having a CAD system that automatically logs these types of things within the server. Though this feature is mainly for staff to ensure there are no rule breaks and troubleshoot vehicle issues.

**Additional context**

**Comment by ExpDev07** [comment]
Hello. I tried using your name and banning a player locally on my machine and it worked fine? The issue could be the server's database encoding. Can you ban people in-game perfectly fine?

**Comment by ExpDev07** [comment]
You can now preview vehicles in their edit character page. To get updated version, run the commands:

```
npm install
npm run prod
```

Then start the server.
