### ISSUE TITLE
404 Error while removing a blacklist identifier 

### ISSUE THREAD

**Issue by GuArDiAn-ops** [ExpDev07/legacy-rp-admin-v3#301]
**Describe the bug**

**To Reproduce**
Ban any identifier and refresh your browser and remove the identifier from the list. But it removes the identifier from the list 

**Expected behavior**

The 404  Not Found error should not be displayed on removing the identifier.

**Screenshots**
https://gyazo.com/7826efe6d0bfdd167f4c316e898055e3
https://gyazo.com/19dfd2f7082789efb5072ecac618635b

**Comment by milan60** [comment]
Can't reproduce this. Tried multiple identifiers and all of them worked perfectly fine
