### ISSUE TITLE
Server overview wont display correct joined/queued 

### ISSUE THREAD

**Issue by GuArDiAn-ops** [ExpDev07/legacy-rp-admin-v3#311]
**Describe the bug**

**To Reproduce**
add a new server to the overview. it wouldnt display the numbers correctly just a "/". 

**Expected behavior**
Display correct number of joined and queued.
**Screenshots**
https://media.discordapp.net/attachments/872835139820982323/892758174841581618/unknown.png

**Comment by milan60** [comment]
Related to the not so recent switch to /world.json instead of /connections.json

**Comment by milan60** [comment]
Seems to be cause by the fact that c3s1.op-framework.com doesn't point to the correct server ip anymore.

![image](https://i.imgur.com/sMyhisM.png)
