### ISSUE TITLE
Church in city

### ISSUE THREAD

**Issue by AnfewMac** [ExpDev07/legacy-rp-admin-v3#376]
**Describe the bug**
We "The Gambettis" flew in today to find out the church that we use for ceremonies and business is no longer available. We are curious is to if this was a bug in the most recent update or if it was taken out in general. We use the church for our "Italian Family" promotions and also have hosted weddings in the past for people within the city. We have also used it as a place of refuge for people during purge nights, halloween murder nights etc. We would very much like it if this was back in the city if it was taken out. Thank you

**Comment by CloudTheWolf** [comment]
This git is for the Admin Panel.
I think this would fall more under the Assets Issue Tracker.  (Here: https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues)
