### ISSUE TITLE
More in depth job information/features in the panel

### ISSUE THREAD

**Issue by Vedder742** [ExpDev07/legacy-rp-admin-v3#38]
**Is your feature request related to a problem? Please describe.**

I have received many reports regarding people abusing paychecks in-game through all the jobs.
Many people who have held any RP roles in businesses, state RP, Department of justice, etc slip by and continue to capitalize on their previous paychecks even after leaving those positions. Some of them have actually never even made any RP contribution to begin with. I think this paycheck abuse is super scummy and falls under FailRP

At this time this is difficult to fight against, staff members can only see a person's job through the admin panel, but not their "position" or "department" (which actually determines the paycheck). Nor can we change their job through the panel, they must be connected to the server with us so we can do it with the commands.

**Describe the solution you'd like**

Admin panel features that would allow staff members to see, change or reset player jobs, departments, and positions.

**Describe alternatives you've considered**

In the meantime, I have set up a google drive database that would at least allow us to track businesses and their employees steam names. Which will hopefully limit the number of people who slip by unnoticed.

**Comment by ExpDev07** [comment]
https://github.com/ExpDev07/legacy-rp-admin-v3/pull/39

**Comment by ExpDev07** [comment]
You can now see and reset players' jobs through their respective character panel. At the moment, you can only reset, not change. The reason is I do not have an overview over available jobs, departments, nor positions (not sure if there's a database table for it, I at least don't have it).

Remember to 
```
git pull
composer install
npm install
npm run prod
```

Then start the server.
