### ISSUE TITLE
Stock/Company tablet/Account balance in Admin Logs (Suggestion/Recommendation)

### ISSUE THREAD

**Issue by GuArDiAn-ops** [ExpDev07/legacy-rp-admin-v3#40]
**Is your feature request related to a problem? Please describe.**
There should be visible cash visible in logs/panel if someone has stored some money in their company/account balance
**Describe the solution you'd like**
The way there is an area that shows a players vehicles a tab or area can be added showing balance and in company account.
**Describe alternatives you've considered**
A feature that either shows the money or cash of the player including the company balance or account or it can be added in a below section or a new section can be made.
**Additional context**

**Comment by ExpDev07** [comment]
Can you please be more descriptive? Do you want a character's stock balance to show up or the companies they own?

**Comment by GuArDiAn-ops** [comment]
The stock balance. Any amount they store in the company account balance should be visible in logs separately or combines with total money.

**Comment by ExpDev07** [comment]
![image](https://user-images.githubusercontent.com/10024730/102707611-e046cd80-429c-11eb-9d07-a3dede9dae8d.png)

Like this? @GuArDiAn-ops

**Comment by GuArDiAn-ops** [comment]
@ExpDev07 yes this is perfect just how I was suggesting!

**Comment by ExpDev07** [comment]
Ok, I will merge that PR now and the feature will be added.

Remember to
```
git pull
npm run prod
```

Then start the server.

**Comment by GuArDiAn-ops** [comment]
Is this a combination of the company account and the shares account in the tablet ?

**Comment by ExpDev07** [comment]
I'm not sure what it is. It references the "stock_balance" column in the database. You'd almost have to ask InzidiuZ what it is. @GuArDiAn-ops
