### ISSUE TITLE
Problems with the panel (Legacy Italia)

### ISSUE THREAD

**Issue by Kryte** [ExpDev07/legacy-rp-admin-v3#443]
**Describe the bug**
The Live Map has totally stopped working.

**To Reproduce**
1. Go to 'Data'
2. Click on 'Live Map'
3. Look under the word "Live - Map"
4. See error 'Data for c5s1 not available: Unauthorized (route)'

**Expected behavior**
As has always been the case, the players should be seen inside the map with the information below the page

**Screenshots**
![live map](https://user-images.githubusercontent.com/57660199/162577616-94a4f5c8-5f79-45c1-af46-a9fefa848d35.png)

**Comment by twooot** [comment]
Should be fixed
