### ISSUE TITLE
Problems with the panel (Legacy Italia) Pt.2

### ISSUE THREAD

**Issue by Kryte** [ExpDev07/legacy-rp-admin-v3#444]
**Describe the bug**
The search player by ID function has stopped working

**To Reproduce**
1. Go to 'Managment'
2. Click on 'Player'
3. On 'Current Server ID' type any number and click on 'Search Player'

**Expected behavior**
The panel should show the information of the player you are looking for

**Screenshots**
![Player](https://user-images.githubusercontent.com/57660199/162577909-88fc6552-4918-4f6d-aa97-aa6a7991c48a.png)

**Comment by twooot** [comment]
Fixed
