### ISSUE TITLE
Temproary bans and keeping a record of bans

### ISSUE THREAD

**Issue by Masik52** [ExpDev07/legacy-rp-admin-v3#46]
**Is your feature request related to a problem? Please describe.**
Currently while within the city we can issue a duration ban. The staff team on the NA / EU server is looking at going to more times bans rather than having everything be an indefinite ban. It would be great if we’d be able to issue a timed ban on the web panel as well as currently to my knowledge it is only an indefinite ban option. 

**Describe the solution you'd like**

the ability to issue a timed ban on the web panel but also have a new section created that has a historical log of any bans the account has received so there is a record when the ban timer expires of what they were banned previously for. 

**Describe alternatives you've considered**

currently we utilize the warning field to notate if someone has been banned previously as well as a spreadsheet. I feel it would be cleaner looking if we had a separate section that logged any bans

**Additional context**

**Comment by ExpDev07** [comment]
@Masik52 You think it's okay the temporary ban feature will only be available on chrome? Firefox does unfortunately not support "datetime-local" input field, which means I'll have to find and use a library (see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local#Browser_compatibility). Or do you think many would be upset about it not being available on Firefox?

**Comment by ExpDev07** [comment]
Hello @Masik52 , I am almost done with this feature (see attached GIF), but I cannot see in the database definition I have received that there are any columns for ban expiration. You would have to reach out to Inzidius about this and get back to me.

https://user-images.githubusercontent.com/10024730/103433299-15351780-4bef-11eb-9b7e-81d5e1430c8f.mp4

**Comment by Masik52** [comment]
Will do. I can check with other NA/EU staff members to see if they use chrome I typically use that or edge at the moment.

**Comment by ExpDev07** [comment]
@Masik52 All Chromium based web browsers will work, so that's for example Chrome, Edge, Opera, etc.

**Comment by ExpDev07** [comment]
Feature has been completed.
