### ISSUE TITLE
error 504

### ISSUE THREAD

**Issue by Milan345** [ExpDev07/legacy-rp-admin-v3#469]
**Describe the bug**
it says error 504

**To Reproduce**
1. Go to players, put the steam identifier
2. Click on right arrow, to access the profile
3. See error
note: its happening only with a player, if required I'll update it with the steam identifier

**Expected behavior**

**Screenshots**
ss link: https://cdn.discordapp.com/attachments/902193697905598535/973541145265197096/unknown.png
clip link: https://streamable.com/7een8h

**Comment by twooot** [comment]
Should be fixed now
