### ISSUE TITLE
Cant add vehicles to garage via add vehicle

### ISSUE THREAD

**Issue by ItsGUARDIAN** [ExpDev07/legacy-rp-admin-v3#484]
**Describe the bug**
Cant add vehicles to garage via add vehicle (Superadmins) via player profile

**To Reproduce**
Open player profile and click on add vehicle it wouldnt display anything

**Expected behavior**
Like before clicking the arrow would usually give you a drop down menu of vehicle to select from or you could type it and vehicles matching that initial alphabets would display to add to garage.
**Screenshots**
[Cant add vehicles to garage via add vehicle](https://gyazo.com/9e43d347e5a66a67a615277ed8ca1d8c)

**Comment by twooot** [comment]
Fixed
