### ISSUE TITLE
Character name searching

### ISSUE THREAD

**Issue by mxttx** [ExpDev07/legacy-rp-admin-v3#49]
**Is your feature request related to a problem? Please describe.**
Sometimes people have an unrelated steam and discord name so it is hard to lookup a player if we do not know either of these, but instead we know them by their character name(s).

**Describe the solution you'd like**
A new "Search by Character Name" with "First name" / "Last name" fields added to the Players section of the panel.

**Describe alternatives you've considered**
I do not believe there could be any alternate way to search character names, it does not make sense to do this on the Logs section of the panel, but it may be possible.

**Additional context**
When inputting First name and Last name, it should only display steam users in our databases that match (not case sensitive) or include the search string in their name (e.g. if we search for First name "Alex", ideally "Alexis" should show up as well, this helps in a lot of cases for Staff in case we don't know the spelling of the name).

**Comment by ExpDev07** [comment]
Hmm, you don't think dedicating a own page to character search would be better?

**Comment by mxttx** [comment]
That works too!

**Comment by GuArDiAn-ops** [comment]
Would it be possible to add filter such as CID and vehicle number if possible to search a character sometimes you got a few people with the same name just an extra alphabet repeated at the end.

**Comment by ExpDev07** [comment]
Yes @GuArDiAn-ops

**Comment by ExpDev07** [comment]
Added.
