### ISSUE TITLE
Picking up a notepad under action shows as "consoleName"

### ISSUE THREAD

**Issue by ItsGUARDIAN** [ExpDev07/legacy-rp-admin-v3#509]
**Describe the bug**

**To Reproduce**
Create a notepad text ingame drop and and pick it up. When you search for notepad you would see "consoleName picked up a notepad with text `text`.'' under the action table but you cannot search it under action as c

**Expected behavior**
It should display notepad picked up under actions table.
**Screenshots**
https://gyazo.com/521defdc8878e111f5f72241f48b51de

**Comment by InZidiuZ** [comment]
I fixed this. It was an issue on the framework, not the admin panel.
