### ISSUE TITLE
Queue display should show time spent in queue

### ISSUE THREAD

**Issue by ItsGUARDIAN** [ExpDev07/legacy-rp-admin-v3#510]
**Is your feature request related to a problem? Please describe.**
Queue display in panel should show time spent in queue in minutes and hours.
**Describe the solution you'd like**
So the queue display in the panel could show mins or hours player has spent in the queue 
**Describe alternatives you've considered**
using the api to check the time spent but it displays in seconds usually so it would be efficient if it could have a table for duration next to the position and priority type which could display in minutes or hours
**Additional context**

**Comment by coalaura** [comment]
done
