### ISSUE TITLE
Character owned vehicle's display names

### ISSUE THREAD

**Issue by mxttx** [ExpDev07/legacy-rp-admin-v3#52]
**Describe the bug**
May not be a bug, but the flatbed (tow truck) and the rumpo (weazel news van) currently display as their uint32 id rather than their name on the panel. This is frustrating for me when I am trying to complete my job in roleplay, I have to look up each time what these cars are, replace the id with the real name and then place it on the documents it needs to be on. Quality of life update would be very much appreciated! I have been as detailed as possible.

**To Reproduce**
*An example for the rumpo (weazel news van)*
1. Go to Legacy EU/NA's panel and search for user "Matt;)";
2. Click on character "Rolf Lions";
3. Scroll down to owned vehicles;
4. Notice the rumpo (weazel news van) is listed as it's uint32 id (1162065741) instead of it's name.

*An example for the flatbed*
1. Go to Legacy EU/NA's panel and search for user "Matt;)";
2. Click Edit on character "Miles Sullivan";
3. Scroll down to owned vehicles;
4. Notice the flatbed (tow truck) is listed as it's uint32 id (1353720154) instead of it's name.

Alternatively find a character on a server's panel you have access to and search for a character with these specific cars.

**Expected behavior**
Instead of the uint32 id showing for these specific cars, the name should show instead.
If not possible or unknown why this happens to these specific cars, catch them separately i.e. if display name is '1162065741', instead show 'rumpo (weazel news van)'.

**Screenshots**
https://imgur.com/a/OyLLKe6

**Comment by ExpDev07** [comment]
This is weird behavior indeed. Only reason I could think of is because InZidius stores the uint32 id in the name column for those specific vehicles. I could easily fix this in the server panel by just doing the conversions runtime, however, it might be better to address the source of the problem?

**Comment by mxttx** [comment]
I'll dm InZidiuZ to see what he can do then I will get back to you.

**Comment by mxttx** [comment]
From InZidiuZ:
It's like that due to some backward compatibility from an older (now deprecated) version of the framework
It's set to be removed though so it won't be an issue then
Don't think there's a need to manually resolve it from Marius' side

**Comment by InZidiuZ** [comment]
Four 'special' vehicles are currently stored in their JOAAT hash instead of the model name. The four vehicles are as following:

1162065741 = rumpo
-956048545 = taxi
1353720154 = flatbed
-2137348917 = phantom

And *if* you want to display the vehicle names instead of the model name, [here's an almost complete Lua table](https://pastebin.com/ShJGCfGT) of them.
