### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by Mac-Womack** [ExpDev07/legacy-rp-admin-v3#520]
![image](https://user-images.githubusercontent.com/100077289/185005706-d8d4b106-a340-4a24-a938-ce783ab500ff.png)

**Comment by twooot** [comment]
What are you trying to do?

**Comment by Mac-Womack** [comment]
I'm trying to instal the menu to my fivem qb server

**Comment by twooot** [comment]
Its not a menu, Its not a fivem resource either. Its an admin panel for the op framework and not qbcore
