### ISSUE TITLE
Search by ban reason in all bans

### ISSUE THREAD

**Issue by ItsGUARDIAN** [ExpDev07/legacy-rp-admin-v3#529]
**Is your feature request related to a problem? Please describe.**

The idea was to be able to search bans with a specific ban reason such as cheater or modder with a search bar in ban section to find bans with the same reason effectively

**Describe the solution you'd like**

**Describe alternatives you've considered**

Addition of a search bar where all bans can be searched by ban reason and display only bans with that specific ban reason

Considered scrolling through all bans but with number of bans that might not be an effective way if the community has over 500-1k bans or over.
**Additional context**

**Comment by coalaura** [comment]
this is done
