### ISSUE TITLE
Screen Capture

### ISSUE THREAD

**Issue by KaiEagle** [ExpDev07/legacy-rp-admin-v3#545]
**Describe the bug**
When trying to record someone's screen we are getting "Failed to capture screen!"

**Expected behavior**
Record the duration amount of screen reply of someone

**Screenshots**
https://img.kaieagle.me/u/EF6rdCT.png

**Comment by coalaura** [comment]
idk if this is still an issue but i am unable to reproduce this. What cluster is this on?

**Comment by KaiEagle** [comment]
> idk if this is still an issue but i am unable to reproduce this. What cluster is this on?

It's fixed now
