### ISSUE TITLE
Player Status while in BR , Arena

### ISSUE THREAD

**Issue by Vikky98** [ExpDev07/legacy-rp-admin-v3#554]
**Describe the bug**
When someone Joins Arena , BR  or use Zombie Pill , at that time when we check his status on panel to check SS , it shows offline on our Web Panel.

**To Reproduce**
1. Go to 'Management'
2. Click on 'Player and put players steam id who's in Arena or something '
3. Scroll to 'at Top'
4. You'll see that even when player is in Server his status is offline on Panel.

**Expected behavior**
Instead of Offline status that must be Online  .

**Screenshots**
ATM Server Id 129 is in Server Playing Arena Match https://i.imgur.com/OSw9yxb.jpeg
But on Panel his status is offline. https://i.imgur.com/o4HeTjN.jpeg

**Comment by coalaura** [comment]
fixed
