### ISSUE TITLE
Wrong log created with the command /voice_debug

### ISSUE THREAD

**Issue by AvhiGaming** [ExpDev07/legacy-rp-admin-v3#556]
**Describe the bug**
When you use the command '/voice_debug' in game then the panel creates the log of being revived 

**To Reproduce**
1. Use '/voice_debug' in-game
2. Move to the admin panel
2. Go to 'Logs'
3. Click on 'Server Logs'
4. Check there for the recent log created

**Expected behavior**
Instead of creating the Log of getting revived it should create the log that player has Toggled the Voice Debug command

**Screenshots**
In Game:
https://gyazo.com/33e04cb4ea6bb38c503f82a8bfe65de7
Admin Panel:
https://gyazo.com/71496c17cd771a2d761e3453ed53b0e8

**Comment by twooot** [comment]
that would be a framework issue
