### ISSUE TITLE
Logging /ban in game

### ISSUE THREAD

**Issue by mxttx** [ExpDev07/legacy-rp-admin-v3#56]
**Is your feature request related to a problem? Please describe.**
The panel currently logs when you ban someone with an expiry date on the panel with a warning, it would be good if it also logged a /ban in-game with a warning too.

**Describe the solution you'd like**
A warning placed on the banned persons account when they are banned FROM THE CITY. This already happens when banning someone from the panel.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by InZidiuZ** [comment]
This would be very difficult to do and only possible with some crazy 'hack' from Marius' side what I know. Instead, I've implemented this feature directly into the framework, so whenever you use the 'ban' command to ban someone, it should now insert a warning into the `warnings` table.
