### ISSUE TITLE
"Ghost" bans

### ISSUE THREAD

**Issue by mxttx** [ExpDev07/legacy-rp-admin-v3#57]
**Describe the bug**
Sometimes it shows users are banned on the panel but they are actually not banned, it is grabbing a ban from someone else and putting it on their panel profile. They are able to connect to servers properly, it just confuses the staff members involved. We have dubbed them "Ghost" bans for now, bans that don't actually exist. 

**To Reproduce**
It is unknown how this is reproduced. I first encountered this issue around 7-9 months ago where we would see new "Ghost bans" every other week. This stopped at around June and they've recently made a return with us finding new examples of said "bans" every other day.

**Expected behaviour**
Go onto a profile of a person who is clearly not banned, and it shows they are not banned, instead of a ban being pulled out of the database and being displayed.

**Screenshots**
https://cdn.discordapp.com/attachments/686057091475046451/810956089654247464/I_never_did_this.jpg
Example of a staff member that is displayed as banned but can connect properly.

For clarification, the one's I have seen are definitely from banning on the panel. A quick search in the logs shows no results https://prnt.sc/zn0nye.

**Comment by ainstaylor** [comment]
![2](https://user-images.githubusercontent.com/79113086/107989143-7bbc9c00-6fc9-11eb-8758-122207cb517f.png)

I know that this ban was issued by Nuzi but not for this player - this player is not banned.

**Comment by ainstaylor** [comment]
![msedge_Ln36mwP0xc](https://user-images.githubusercontent.com/79113086/108199531-170e5800-7115-11eb-8db2-bf18ebb2b455.png)

I'm not banned but on the panel it shows I am

**Comment by ExpDev07** [comment]
This is most likely the result of the players sharing either of the following attributes:
- steam
- rockstar license 
- discord tag
- Xbox live tag
- IP address

There could however be a bug as well.

**Comment by mxttx** [comment]
Definitely a bug, Ains says he does not share any of those attributes with anyone. I myself have been shown as "banned" like this too and I know for a fact I don't. Ex-staff members back in the day said if we was to unban these "ghost banned" accounts, i.e. ainsley (again, you know they are "ghost banned" because they can connect to the server without problems) then the original perpetrator will also be unbanned.

This makes be think that it is showing someone else's ban for sure, and unbanning the "ghost banned" account removes the same ban on the original account as well. 

This would not be the case if a user was to share any of the above with someone else, they would get an identical but different id ban placed on their account to differentiate the two, i.e. if one was unbanned the other would not be. This has been tested in the field too, both accounts (if they were shared) would have to be unbanned for them to be able to play as they'd just be automatically banned again like you said for sharing said attributes.

**Comment by ExpDev07** [comment]
Alright. If you unban the "ghost", the original perpetrator would be unbanned as well. What if you again banned either the "ghost" or perpetrator, would both persons be shown as banned again? Or would it work as intended?

**Comment by InZidiuZ** [comment]
I am almost certain that these 'ghost bans' come from IPs. For some reason, the FiveM/FXServer seems to often 'leak' IP addresses to players that they don't belong to, causing it to be logged to their account. Since that discovery, all OP-FW server bans (local & global), have stopped using IPs to track them entirely. Prior to that, these 'ghost bans' would often prevent players from joining the server, prompting them someone else's ban.

**Comment by GuArDiAn-ops** [comment]
I live in a different country than most of our players from my subdivision. So my ip matching with anyone is pretty rare my profile yesterday I didnt have any ghost ban and I have a ban reflecting of someone I banned from the web panel a few mins back.
steam , rockstar or discord was never shared with anyone

**Comment by mxttx** [comment]
It's not on your side @GuArDiAn-ops - something to do with the database. I've seen the problem InZidiuZ stated before whilst working on emulators and websites. Forced us to stop using ipbans as a lot of users would be involved. I know it's not common practice to log ip addresses, but when we did it was clear to see that they were the same for a lot of people.

Hopefully this can be fixed soon by looking into it more carefully, perhaps people are getting the proxy ip address linked to them instead of their actual ip address? @InZidiuZ (Not sure if there is a proxy in use, but that is almost always the case)
