### ISSUE TITLE
Phone Logs

### ISSUE THREAD

**Issue by KaiEagle** [ExpDev07/legacy-rp-admin-v3#577]
**Describe the bug**
Phone Logs of cluster 8 is not working.

**To Reproduce**
1. Go to 'Logs'
2. Click on 'Phone Logs'
3. 404 | Not Found

**Expected behavior**
The Phone Logs of cluster c2 (Test Server) is working fine but for c8 (India) is not working.

**Screenshots**
https://img.kaieagle.me/u/GJqTO5K.png

**Comment by twooot** [comment]
fixed
