### ISSUE TITLE
Users' playtime is mislabeled

### ISSUE THREAD

**Issue by InZidiuZ** [ExpDev07/legacy-rp-admin-v3#58]
**Describe the bug**
The 'playtime' indicates that the number displayed is in minutes, but it is meant to be seconds.

**To Reproduce**
On the 'players' page:
1. Go to 'Players'.
2. See the 'playtime' columns say minutes instead of seconds.

On a user's profile page:
1. Go to 'Players'.
2. Go to any player's profile.
3. See the 'playtime' box in the top-left corner saying minutes instead of seconds.

**Expected behavior**
It should say seconds instead of minutes.

**Screenshots**
[A screenshot of the issue on the 'Players' page](https://gyazo.com/ca76f6202f168873747501f8f60e72fa).
[A screenshot of the issue on a user's profile page](https://gyazo.com/a22ddc458f3be690a58da4ab15f9e299).

**Additional**
I'm not sure what you'd like to do, but possibly displaying the value in a more user-friendly way could be good. Instead of just giving the amount of seconds of playtime, maybe it could give you a more sensible understanding of it by giving you minutes, hours, and perhaps even days.

**Comment by milan60** [comment]
Here's a small JavaScript function to format seconds to days, hours, minutes and seconds.
```javascript
function fmtSeconds(c) {
    return [['d', 86400], ['h', 3600], ['m', 60], ['s', 1]].reduce((r, s) => {
        let t = Math.floor(r[1]/s[1]);
        return [r[0] + (t + s[0]), r[1] - t * s[1]];
    }, ['', c])[0].replace(/^(0.\s)+/gm, '');
}
```
