### ISSUE TITLE
'Next' and 'previous' pages doesn't work

### ISSUE THREAD

**Issue by InZidiuZ** [ExpDev07/legacy-rp-admin-v3#59]
**Describe the bug**
When on a page that has other pages (i.e. the 'logs' page and the 'users' page), the "Next" and "Previous" page buttons doesn't work.

For some reason when I tried to test this locally, they seemed to function. But on panels in production, they don't seem to work at all. Appending `?page=x`, however, does let you go to the different pages without issue. (appending `?page=100000` gives you no logs.)

**To Reproduce**
1. Go to the 'Players' page.
2. Press "Next".
3. It loads infinitely.

**Expected behavior**
It should load the next page without problems.

**Screenshots**
[Here's a gif of it not working](https://gyazo.com/a2040120b9a15b5a8f38721087247a93).

**Comment by ravicant** [comment]
here what i found in the console https://i.ravicant.in/7hnQYL0DE

**Comment by ExpDev07** [comment]
In your enviroment variables, make sure `APP_URL` is set to `https://c3.legacy-roleplay.com` with `https` in front. It's trying to call the https version.

**Comment by InZidiuZ** [comment]
I changed the `APP_URL` like [this](https://gyazo.com/97a5b2a1b22344a4511f68f0fad0dc77), but after restarting the server, the same thing happens with the exact same error as posted by @ravicant. I also tried running `npm run prod` but that didn't seem to change anything.

**Comment by ExpDev07** [comment]
Is the site content provided through Cloudflare? In which case, it's a proxy issue.

**Comment by InZidiuZ** [comment]
Yes, it is proxied through Cloudflare.

**Comment by Yusuf0007** [comment]
Idk I am not yet able to load the 2nd page of the admin panel. Is this problem solved yet?

**Comment by ExpDev07** [comment]
Fixed, just pull new version.

**Comment by Yusuf0007** [comment]
how could I pull? I am still unable to load other pages
