### ISSUE TITLE
Ability to 'edit' bans

### ISSUE THREAD

**Issue by InZidiuZ** [ExpDev07/legacy-rp-admin-v3#61]
**Is your feature request related to a problem? Please describe.**
Whenever you want to edit a ban, either when you want to edit the ban reason or the time of expiration, you have to lift the ban and then add it again.

**Describe the solution you'd like**
An ability to edit ban reasons and ban lengths. Perhaps also being able to change a ban from permanent to temporary.

**Describe alternatives you've considered**
Unbanning the player and then banning them again.

**Comment by milan60** [comment]
Can be closed due to recent merge #119
