### ISSUE TITLE
Properties wont show all the properties under player's info

### ISSUE THREAD

**Issue by ItsGUARDIAN** [ExpDev07/legacy-rp-admin-v3#643]
**Which clusters panel is this on?**
c2, c3, etc.
c8
**Describe the bug**
So in the properties section under a character's properties, the properties shown are only those that are under the player's name and do not show the houses with shared keys, as it shows a lot more info on all houses used by the player in the database.

**To Reproduce**
1. search any character's house details in the character details screen.
2. The info wont be same as available on the database such as shared keys.

**Expected behavior**

**Screenshots**
https://i.itsguardian.xyz/u/n3InJJcn.png Additionally on C8 character id 14 has number of accesses(me) but they aren't visible
https://i.itsguardian.xyz/u/VsJlL3EZ.png ingame tablet
More data is available if you check c8 character 14 house and shared keys.

**Comment by coalaura** [comment]
all done
