### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by InZidiuZ** [ExpDev07/legacy-rp-admin-v3#66]
**Is your feature request related to a problem? Please describe.**
A lot of non-English communities use this admin panel. Because of that, adding localization is something I believe would be a great addition.

**Describe the solution you'd like**
A localization system, allowing players to set their preferred language.

**Additional context**
On OP-FW, the server has its own 'default language' set to whatever the language of the community is, then all of the players on the server has the ability to change their language to another one if they'd like. Perhaps something like that would be good here.

**Comment by GuArDiAn-ops** [comment]
Would be nice to be able to change the timezone on the panel itself if you live in different timezones

**Comment by milan60** [comment]
I added localization for the admin panel in a new branch, it would move all labels and stuff to JSON files which would then have to be translated.
