### ISSUE TITLE
Error While Fetching Player Data of new player on web panel after latest update

### ISSUE THREAD

**Issue by Vikky98** [ExpDev07/legacy-rp-admin-v3#662]
**Which clusters panel is this on?**
c8

**Describe the bug**
After New Update , Player data is fetched on basis of their rockstar license , before it use steam hex . at that time we can open each and every player profile even with few mins of playtime one . but now when we try to open player profile with few mins to an hour or two playtime . there is error pops up.

**To Reproduce**
1. Go to '...'player section in management
2. Click on '....'any player with few mins of playtime
4. See error TypeError
App\Player::getSteamIdentifier(): Return value must be of type string, null returned

**Expected behavior**
it must return player data like before.

**Screenshots**
https://i.imgur.com/DeLPsny.png ,

**Comment by coalaura** [comment]
this should be fixed

**Comment by Vikky98** [comment]
Appreciated . and one more thing , I observed that on Live map section EMS count always shows zero even when EMS is on duty ingame. https://i.imgur.com/LinlhHd.png  Sent from Mail for Windows From: LauraSent: 22 December 2022 06:56 AMTo: ExpDev07/legacy-rp-admin-v3Cc: Vikky98; AuthorSubject: Re: [ExpDev07/legacy-rp-admin-v3] Error While Fetching Player Data of new player on web panel after latest update (Issue #662) this should be fixed—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
