### ISSUE TITLE
EMS count on Live Map in Web Panel

### ISSUE THREAD

**Issue by Vikky98** [ExpDev07/legacy-rp-admin-v3#665]
**Which clusters panel is this on?**
c2, c3, etc.
c8
**Describe the bug**
I've been observing this for quite few times now that on live map in our web panel, on duty police count, staff count is accurate but EMS count always shows zero even if EMS is on duty at that time. And if we track that player who's on duty as EMS, in description under player's character name it shows -on foot and so on. 
**To Reproduce**
1. Go to '...'live map
2. Click on '....'search box to enter server id of an onduty EMS player
4. See error there's no mention on that players as - onduty (EMS) nor in EMS count

**Expected behavior**
As police count and staff count it must show EMS count when they're on duty.

**Screenshots**
https://imgur.com/a/I0SECaJ player log as on duty
https://imgur.com/a/Yr9KwI4 status of same player on live map.

**Comment by coalaura** [comment]
fixed
