### ISSUE TITLE
Logical rebranding of the admin panel

### ISSUE THREAD

**Issue by InZidiuZ** [ExpDev07/legacy-rp-admin-v3#67]
**Is your feature request related to a problem? Please describe.**
OP-FW is not directly related to Legacy, and the intent is that Legacy simply relies on OP-FW to provide the game servers and other services. With that in mind, it doesn't make that much sense for this admin panel to be called 'legacy' and be full with hardcoded Legacy branding.

**Describe the solution you'd like**
My suggestion would be to rebrand it to not announce any 'affiliation' with Legacy, and instead replace that with OP-FW.

**Additional context**
This isn't a big deal, but I figured I'd bring it to your attention and see if you'd like to change it.

**Comment by ExpDev07** [comment]
Do you have any OP-FW assets like logos, etc. Link here.

**Comment by InZidiuZ** [comment]
[Here's a link](https://plik.root.gg/#/?id=CgMsPbmcLJpUrwbJ) to all the files relating to the the current OP-FW assets & logos that I could find. There's also a discord guild for it [here](https://discord.gg/yRBWkjb).
