### ISSUE TITLE
Cannot edit car owner cid

### ISSUE THREAD

**Issue by ItsGUARDIAN** [ExpDev07/legacy-rp-admin-v3#675]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
So when changing owner cid in the panel to transfer vehicles from user to other the new cid wont be saved any the vehicle is present on the original owner of the vehicles editing and saving new cid wont apply the new owner's cid
**Describe alternatives you've considered**
New cid should be saved and the vehicle should be transferred 
**Additional context**
Replicated on c2 after having this issue on c8
https://i.itsguardian.xyz/u/yWZKJAwpqqdSzoLa75aJOte970Swe20V.gif

**Comment by coalaura** [comment]
should be fixed now
