### ISSUE TITLE
Live server information on the admin panel

### ISSUE THREAD

**Issue by InZidiuZ** [ExpDev07/legacy-rp-admin-v3#69]
**Is your feature request related to a problem? Please describe.**
This isn't really related to a problem, it's more so that you can just get some live information about the FiveM server(s) directly on the admin panel.

**Describe the solution you'd like**
I'd like to see a new page called 'Servers' where you can view some information such as framework version, uptime, players and more. Being able to see who's currently online would also be great, and perhaps having a redirect to their user profile on the admin panel.

**Additional context**
This can be achieved by using some of the routes that I have created for the framework. Currently there are only two that would be relevant to this, but I'd be open to add far more for whatever you'd want and/or need.

The two (GET) routes are:
/api.json
/connections.json

You can reach them by going to [this 'example' URL](https://c3s1.op-framework.com/op-framework/api.json).

Some clusters have multiple servers, though, so if this were to be implemented, it would be great to have a way of viewing various servers that have been added to the admin panel.

**Comment by ExpDev07** [comment]
You can now add the servers (see GIF). Will see if I can get a PR in soon to also view the online players.

![site](https://user-images.githubusercontent.com/10024730/119262261-df62f080-bbda-11eb-8d8e-c1f03299ac14.gif)

**Comment by milan60** [comment]
This page now also shows all online players and allows deleting (removing from tracking) servers. I think this issue can be closed @ExpDev07
