### ISSUE TITLE
Invalid cluster "c1"

### ISSUE THREAD

**Issue by VinIsDev** [ExpDev07/legacy-rp-admin-v3#699]
**Which clusters panel is this on?**
c1

**Describe the bug**
When I try run "composer install", makes error "Invalid cluster "ci

**Comment by Havoc454** [comment]
Run "composer install --ignore-platform-req=ext-gmp"

**Comment by coalaura** [comment]
this should no longer be an issue, however this repository is no longer maintained, check https://github.com/coalaura/opfw-admin
