### ISSUE TITLE
Ban and warning gives different times

### ISSUE THREAD

**Issue by ainstaylor** [ExpDev07/legacy-rp-admin-v3#70]
When banning someone using the server command /ban it bans the person as per the server log time. When warning someone via the admin panel it uses GMT time.

https://i.imgur.com/eJ6X2OA.png

**Comment by ExpDev07** [comment]
What does the server use? CET?

**Comment by milan60** [comment]
Server uses EST

**Comment by ainstaylor** [comment]
I actually think me and a few staff members compared log times. The server logs seem to be -9 hours from your local computer time where as if you use the admin panel to create a log (ban or warning) they show as per your local computer time.

**Comment by ainstaylor** [comment]
It may be -7 hours for everyone, I remember checking with a few different people and we figured it was -7 hours or -9 hours for everyone's local time. If it changes to UTC that would be helpful so the time is the same for everyone

**Comment by milan60** [comment]
I'm trying to fix it in a way that it will show the time in whatever timezone that the user viewing the page is in.

**Comment by milan60** [comment]
I believe this has been fixed by #87
