### ISSUE TITLE
Admin site problem

### ISSUE THREAD

**Issue by Yusuf0007** [ExpDev07/legacy-rp-admin-v3#72]
**Describe the bug**
I am facing a problem of admin site as if it take too long to response and if it response then the other option shows error like the picture. I tried clearing caches and browser data as well but it did not worked for me also I tried several browser and its remain same.
![unknown](https://user-images.githubusercontent.com/63628491/112176096-ffe5ed00-8c21-11eb-85af-5ec7de6350fc.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by ExpDev07** [comment]
This is a cloudflare issue not related to `legacy-rp-admin-v3` directly.
