### ISSUE TITLE
hide ban creator when banned or kicked via panel

### ISSUE THREAD

**Issue by ItsGUARDIAN** [ExpDev07/legacy-rp-admin-v3#761]
**Which clusters panel is this on?**
c8

**Describe the bug**
So when hide_ban_creator = true is enabled in the server config and any player is banned or kicked via panel has the ban creator name displayed even though hide_ban_creator = true.

**To Reproduce**
Ban or kick a player via panel and the exit message on them will displayed banned by xyz for reason _______ or you have been kicked by xyz for reason _________

**Expected behavior**
Ban creator can be hidden in panel if the server config is set to true 

**Screenshots**
https://i.itsguardian.xyz/u/skbh2x.png

**Comment by coalaura** [comment]
I'll do this but ![btw](https://i.shrt.day/DALeyudU03.png)

**Comment by coalaura** [comment]
fixed
