### ISSUE TITLE
** Teleporting to GPS Mark/ Waypoint ** 

### ISSUE THREAD

**Issue by Ashraf2112** [ExpDev07/legacy-rp-admin-v3#77]
**Is your feature request related to a problem? Please describe.**
When you want to go to an exact location or trying to find something it takes some time with no clip. 

**Describe the solution you'd like**
If we were able to TP to the exact location that we mark on our Map, it will be faster. For Ex: https://prnt.sc/12nmoei If I want to go a location. There should be an option on the EasyAdmin menu: Teleport To GPS Location/ Marker.

**Describe alternatives you've considered**
N/A 

**Additional context**
https://prnt.sc/12nmr98 
Something like this: https://www.youtube.com/watch?v=CY6tLHYCraA

**Comment by ExpDev07** [comment]
I believe you are in the wrong repository/project. This project has nothing to do with EasyAdmin. This is a web admin panel for OP-FW FiveM.

**Comment by milan60** [comment]
@Ashraf2112 I made a GitHub issue about it on the op-fw GitHub: https://github.com/InZidiuZ/op-framework-issue-tracker/issues/1832
