### ISSUE TITLE
Clickable Links

### ISSUE THREAD

**Issue by Cironite** [ExpDev07/legacy-rp-admin-v3#9]
**Is your feature request related to a problem? Please describe.**
Inability to click links
**Describe the solution you'd like**
Clickable links in the warnings
**Describe alternatives you've considered**
none
**Additional context**

**Comment by ExpDev07** [comment]
Added as of https://github.com/ExpDev07/legacy-rp-admin-v3/commit/d1e9d27b25d338331ff4b10a19230b446577d575.
