### ISSUE TITLE
Multiple characters not animating properly

### ISSUE THREAD

**Issue by milan60** [ExpDev07/legacy-rp-admin-v3#91]
**Describe the bug**
Only the first 3 character cards load on the Player page.

**To Reproduce**
1. Go to a Player page who has more than 3 characters

**Expected behavior**
All the character cards to show

**Screenshots**
![one](https://i.imgur.com/tO30eMz.png)
![two](https://i.imgur.com/xgoFfe8.png)

**Comment by ExpDev07** [comment]
Hello! Could you open a PR to just remove the data-aos-* attributes on the character cards?

**Comment by milan60** [comment]
Will do

**Comment by milan60** [comment]
Done

**Comment by ExpDev07** [comment]
Fixed.
