### ISSUE TITLE
Ability to edit character birthdays

### ISSUE THREAD

**Issue by milan60** [ExpDev07/legacy-rp-admin-v3#93]
**Is your feature request related to a problem? Please describe.**
*I want to be able to edit the birthday of a character*

**Describe the solution you'd like**
*In the character edit screen the ability to change the birthday*

**Describe alternatives you've considered**
*No real alternative, there is no way of editing birthdays at the moment*

**Additional context**

**Comment by ExpDev07** [comment]
I'll see if I can get this pushed out today.

**Comment by ExpDev07** [comment]
Added.
